### ISSUE TITLE
All translate gone in zh_Hant_TW.csv

### ISSUE THREAD

**Issue by kfluk** [mageplaza/magento-2-chinese-taiwan-language-pack#3]
Hi there, I found zh_Hant_TW.csv was gone. is there anything wrong? thanks.

**Comment by kfluk** [comment]
I found main stream zh_Hant_TW.csv is empty. Please advise what's going on? I like to translate the language.

**Comment by legendhorus** [comment]
Thanks for your report and sorry for any inconvenience.
We have fixed this issue. Please update the latest version or rollback to previous.
